<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Interfaces\" />
		<Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.5.1" />
		<PackageReference Include="MediatR" Version="13.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AirlineBookingSystem.BuildingBlocks\AirlineBookingSystem.BuildingBlocks.csproj" />
		<ProjectReference Include="..\AirlineBookingSystem.Payments.Infrastructure\AirlineBookingSystem.Payments.Infrastructure.csproj" />
	</ItemGroup>

</Project>
